import React from 'react';
import { AIBasicsOverviewDiagram, NestedAIDiagram, BaseRateDiagram, LearningParadigmsDiagram, LearningParadigmsGenericDiagram, NeuralNetDiagram, CapabilityTiersDiagram, AIPipelineDiagram } from './m1-diagrams';
import { TokenizationDiagram, EmbeddingsDiagram, RAGFlowDiagram, FTvsPromptingDiagram, HallucinationMitigationDiagram } from './m2-diagrams';
import { AIStackDiagram, MCPDiagram, AgentTopologyDiagram, AutonomyLevelsDiagram, A2AvsMCPDiagram, SkillsPluginsDiagram, SubagentsDiagram, HooksDiagram, PhishingTriageDiagram } from './m3-diagrams';
import { SOCArchDiagram, PromptInjectionDiagram, AgentAttackSurfaceDiagram, EDRBehavioralDiagram, EmailIdentityDiagram, AIAttackAccelerationDiagram, SOAREvolutionDiagram, SIEMXDRDiagram } from './m4-diagrams';
import { SOCCopilotsDiagram, ThreatIntelHuntingDiagram, DataGovernanceDiagram, DefenseReframingDiagram } from './soc-ops-diagrams';
import { ScalingLawsDiagram, ComputeStackDiagram, MoEDiagram, InferenceServingDiagram, AIEconomicsDiagram, EvalStackDiagram } from './deep-dive-diagrams-a';
import { ReasoningComputeDiagram, GenerativeArchitecturesDiagram, MultimodalUnderstandingDiagram, AlignmentStackDiagram, GovernanceLandscapeDiagram, ContextEngineeringDiagram } from './deep-dive-diagrams-b';
import { AISecurityFrameworksDiagram, SpeechAudioDiagram, ExplainabilityLayersDiagram, AccountabilityChainDiagram, WhyNowDiagram, HorizonMapDiagram } from './course-gap-diagrams';
import { NextWordPredictionDiagram, TrainingVsUsingDiagram, PromptAnatomyDiagram, VerifyBeforeYouShareDiagram, DigitalFootprintDiagram } from './teens-diagrams';
import { EvalDrivenLoopDiagram, GoldenDatasetDiagram, LLMJudgeBiasDiagram, RegressionSuiteDiagram, RedTeamLoopDiagram } from './evals-diagrams';
import { CareAIMapDiagram, PilotToProductionDiagram, DistributionShiftDiagram, ClinicalEvidenceLadderDiagram, SaMDGovernanceDiagram } from './healthcare-diagrams';
import { LegalTaskSuitabilityDiagram, CitationVerificationDiagram, HallucinatedCitationDiagram, PrivilegeDataFlowDiagram, FirmAIPolicyDiagram } from './legal-diagrams';
import { TokensAndContextDiagram, RecommendationFeedDiagram, ConsentAndImagesDiagram, GoodhartsTrapDiagram, NonDeterminismTestingDiagram } from './course-diagrams-c';
import { AmbientScribeFlowDiagram, AutomationBiasDiagram, ClauseExtractionDiagram, RetrievalLimitsDiagram, SupervisionChainDiagram } from './course-diagrams-d';
import { WhyItMakesThingsUpDiagram, AcademicHonestyLineDiagram, SkillsShiftDiagram, BenchmarkHonestyDiagram, TaskVsQualityMetricsDiagram } from './course-diagrams-e';
import { ObservabilityLoopDiagram, SensitivitySpecificityDiagram, LocalValidationDiagram, TARPrecedentDiagram, HumanReviewProtocolDiagram } from './course-diagrams-f';
import { SyntheticMediaTypesDiagram, BiasInEverydayAIDiagram, AICareerMapDiagram, EvalStatisticsDiagram, JailbreakTaxonomyDiagram } from './course-diagrams-g';
import { CostLatencyFrontierDiagram, ReaderAssistanceModesDiagram, ClinicalDriftMonitoringDiagram, ModelChangeControlDiagram, ReviewBurdenShiftDiagram } from './course-diagrams-h';
import { CheckingAIOutputDiagram, MisinformationScaleDiagram, AmplifierNotReplacementDiagram, EvalsAsUnitTestsDiagram, SourcingEvalCasesDiagram } from './course-diagrams-i';
import { SafetyDisclosureFlowDiagram, ImagingAICapabilitiesDiagram, HealthDatasetBiasDiagram, ClinicalGovernanceCommitteeDiagram, DiligenceAtVolumeDiagram } from './course-diagrams-j';
import { StudyingWithAIDiagram, WhenNotToUseAIDiagram, ScepticalNotParanoidDiagram, FootprintOverTimeDiagram } from './course-diagrams-k';
import { WhatToStudyDiagram, KeepLearningDiagram, VibesDontScaleDiagram, CostOfNoEvalsDiagram } from './course-diagrams-l';
import { SharedRubricDiagram, CIForPromptsAndAgentsDiagram, AutomatedRedTeamLimitsDiagram, AUCvsUtilityDiagram } from './course-diagrams-m';
import { CourseScopeSafetyDiagram, DecisionSupportSpectrumDiagram, RegulatoryLandscapeHCDiagram, DeidentificationConsentDiagram } from './course-diagrams-n';
import { LegalScopeSafetyDiagram, WhyLegalExposedDiagram, RedliningFlowDiagram, SanctionsPatternDiagram } from './course-diagrams-o';
import { SupervisingJuniorsDiagram, TechCompetenceDiagram, BillingConsentMalpracticeDiagram } from './course-diagrams-p';
import { SOCTriageScenarioDiagram, SOCBreachScenarioDiagram, SOCPatchScenarioDiagram } from '../course/agentic/SOCScenarioDiagrams';
import { LoopOwnershipDiagram, RunTerminationDiagram, AgentBudgetsDiagram, StuckAgentDetectionDiagram, ScriptVsAgentDiagram } from './course-diagrams-q';
import { ContextAssemblyDiagram, ContextCurationDiagram, ContextOrderingDiagram, ContextCompactionDiagram, MemoryLifetimesDiagram } from './course-diagrams-r';
import { CacheAwareLayoutDiagram, ToolApiDesignDiagram, ToolSchemasDiagram, ToolReturnRecoveryDiagram, ToolErrorsSideEffectsDiagram } from './course-diagrams-s';
import { LoopVerificationDiagram, SubAgentDelegationDiagram, NonDeterminismDiagram, RunTracingDiagram, AgentFailureTaxonomyDiagram } from './course-diagrams-t';
import { CostLatencyRequirementsDiagram, GracefulDegradationDiagram, AgentLoggingDiagram, ApprovalGateDesignDiagram, EscalationOutcomeDiagram } from './course-diagrams-u';
import { RunPresentationDiagram, TrustCurveDiagram, OversightAtVolumeDiagram, ForbiddenActionsDiagram } from './course-diagrams-v';
import { VibecodingMeaningDiagram, WhatYouCanBuildDiagram, WhatNotToBuildDiagram, WeekendSizingDiagram, PrototypeStagesDiagram } from './course-diagrams-w';
import { VibecodingToolsDiagram, PlainLanguageSpecDiagram, OneThingAtATimeDiagram, ScreensAndFlowsDiagram, NotWhatYouPicturedDiagram } from './course-diagrams-x';
import { DescribeTheGapDiagram, BreakingIsNormalDiagram, ReadingErrorsDiagram, GivingAIContextDiagram, DoomLoopDiagram } from './course-diagrams-y';
import { WrongToolDiagram, GoodLooksLikeDiagram, WholeListEveryTimeDiagram, TestWithOthersDiagram, WorkedWhenITriedDiagram } from './course-diagrams-z';
import { AIFeatureWrongDiagram, OtherPeoplesDataDiagram, SecretsAndKeysDiagram, RunawayCostsDiagram, WorksOnMyMachineDiagram, UnreadableCodeDiagram } from './course-diagrams-aa';
import { ClassicThreatModelsDiagram, AIAttackSurfaceMapDiagram, UntrustedModelBoundaryDiagram, LLMDataFlowDiagram } from './course-diagrams-ab';
import { MitreAtlasDiagram, AcceptedRisksDiagram, PromptInjectionDepthDiagram, IndirectInjectionDiagram, LethalTrifectaDiagram } from './course-diagrams-ac';
import { ToolPoisoningDiagram, MemoryContaminationDiagram, ExcessiveAgencyDiagram, AgentLeastPrivilegeDiagram, SandboxEgressDiagram } from './course-diagrams-ad';
import { IrreversibleActionGatesDiagram, StructuredOutputControlDiagram, GuardrailModelsDiagram, DefenseInDepthAIDiagram, AuthorisedExerciseDiagram } from './course-diagrams-ae';
import { SecurityRegressionCIDiagram, AutoAdversarialTestingDiagram, AIIncidentDetectionDiagram, ModelIncidentResponseDiagram, PostIncidentGovernanceDiagram } from './course-diagrams-af';
import { EverythingInTheBoxDiagram, NoMemoryDiagram, WordingMattersDiagram, CommonPromptMistakeDiagram, RolePerspectiveDiagram } from './course-diagrams-ag';
import { ContextConstraintsDiagram, TaskAsOutcomeDiagram, ShowDontTellDiagram, ReasoningFirstDiagram, AskForStructureDiagram } from './course-diagrams-ah';
import { LengthAndToneDiagram, EditableDraftsDiagram, MakeItAskQuestionsDiagram, FourReasonsBadDiagram, DescribeAnswerGapDiagram } from './course-diagrams-ai';
import { SycophancyTrapDiagram, ConfidentFabricationDiagram, ModelSimplyWrongDiagram, ReusablePromptsDiagram, TeamPromptAssetsDiagram } from './course-diagrams-aj';
import { OwnMaterialDiagram, PromptingCeilingDiagram, DocAnswerTestingDiagram, MultiStepAgentTestingDiagram } from './course-diagrams-ak';
import { ScalableHumanReviewDiagram, ProductionTestingDiagram, QualityCostLatencyDiagram, EvalTeamHabitDiagram } from './course-diagrams-al';
import { LLMGovernanceLayersDiagram, AIMisconceptionsDiagram, LLMInfrastructureDiagram } from './course-diagrams-am';
import { VendorDueDiligenceDiagram, SkepticalDemoDiagram, VendorPushbackDiagram, HonestBusinessCaseDiagram, BuyerSituationsDiagram, SecurityPromptingDiagram } from './course-diagrams-an';
import { FirstUseCaseDiagram, ProvingPilotDiagram, SOCMetricsDiagram, AnalystRoleShiftDiagram, StagedAutonomyDiagram } from './course-diagrams-ao';
import { CapstoneWalkthroughDiagram } from './course-diagrams-ap';
import { HealthSourceLadderDiagram, LegalSourceLadderDiagram } from './course-diagrams-aq';
import { HonestMapFinanceDiagram, ModelsNotNewDiagram, WhereItHelpsFinanceDiagram, WherePilotsDieDiagram, OfficeRiskProfileDiagram, ModelRiskFrameDiagram, ExplainThisDecisionDiagram, ProxyDiscriminationDiagram, ModelInventoryDiagram, VendorModelRiskDiagram } from './course-diagrams-ar';
import { ConfidentWrongNumbersDiagram, BacktestOverfittingDiagram, LeakageLookAheadDiagram, RegimeChangeDiagram, CorrelatedModelsDiagram, HumanInTheDecisionDiagram, WhatYouPasteFinanceDiagram, RecordsSupervisionDiagram, GovernanceCaseDiagram, FinanceSourceLadderDiagram } from './course-diagrams-as';
import { ProductBehindTheDemoDiagram, AskDontImagineDiagram, NotListDiagram, StagePlanLedgerDiagram } from './course-diagrams-at';
import { CollapsedSliceDiagram, DemoVsProductWorksDiagram, ChecksWhileYouSleepDiagram, LedgerAfterDemoDiagram } from './course-diagrams-au';
import { WhereDataLivesDiagram, MigrationsBackupsDiagram, AccountsAndResetsDiagram, HiddenServicesDiagram, BelowScreenLedgerDiagram } from './course-diagrams-av';
import { DeployRollbackDiagram, ShippingPipelinePlainDiagram, KnowingItBrokeDiagram, CostAtRealUsageDiagram, ElevenPmEmailDiagram } from './course-diagrams-aw';
import { SoftwareRotDiagram, HandoverTestDiagram, WeekendVsRealProductDiagram, GenuinelyShippableDiagram } from './course-diagrams-ax';
import { AuditScopeSafetyDiagram, AuditAIMapDiagram, FullPopulationTestingDiagram, AuditExposureDiagram, AuditPilotsDieDiagram } from './course-diagrams-ay';
import { ScepticismVsToolDiagram, EvidenceNotOutputDiagram, WorkpaperQuestionDiagram, AuditPasteProblemDiagram, AuditReviewAtVolumeDiagram } from './course-diagrams-az';
import { ModelBehindTheNumberDiagram, ClientAIInventoryDiagram, BlackBoxEstimateDiagram, ModelInControlDiagram, ManagementAIConversationDiagram } from './course-diagrams-ba';
import { InspectorQuestionDiagram, ToolBeforeRelianceDiagram, RecurringEngagementDriftDiagram, AuditJobShiftDiagram, AuditSourceLadderDiagram } from './course-diagrams-bb';

export const DIAGRAM_REGISTRY: Record<string, React.ComponentType> = {
  AIBasicsOverview: AIBasicsOverviewDiagram,
  NestedAI: NestedAIDiagram,
  BaseRate: BaseRateDiagram,
  LearningParadigms: LearningParadigmsDiagram,
  LearningParadigmsGeneric: LearningParadigmsGenericDiagram,
  NeuralNet: NeuralNetDiagram,
  CapabilityTiers: CapabilityTiersDiagram,
  AIPipeline: AIPipelineDiagram,
  Tokenization: TokenizationDiagram,
  Embeddings: EmbeddingsDiagram,
  RAGFlow: RAGFlowDiagram,
  FTvsPrompting: FTvsPromptingDiagram,
  HallucinationMitigation: HallucinationMitigationDiagram,
  AIStack: AIStackDiagram,
  MCP: MCPDiagram,
  AgentTopology: AgentTopologyDiagram,
  AutonomyLevels: AutonomyLevelsDiagram,
  A2AvsMCP: A2AvsMCPDiagram,
  SkillsPlugins: SkillsPluginsDiagram,
  Subagents: SubagentsDiagram,
  Hooks: HooksDiagram,
  PhishingTriage: PhishingTriageDiagram,
  SOCArch: SOCArchDiagram,
  EDRBehavioral: EDRBehavioralDiagram,
  EmailIdentity: EmailIdentityDiagram,
  AIAttackAcceleration: AIAttackAccelerationDiagram,
  PromptInjection: PromptInjectionDiagram,
  AgentAttackSurface: AgentAttackSurfaceDiagram,
  SOAREvolution: SOAREvolutionDiagram,
  SIEMXDRArch: SIEMXDRDiagram,
  SOCCopilots: SOCCopilotsDiagram,
  ThreatIntelHunting: ThreatIntelHuntingDiagram,
  DataGovernance: DataGovernanceDiagram,
  DefenseReframing: DefenseReframingDiagram,
  ScalingLaws: ScalingLawsDiagram,
  ComputeStack: ComputeStackDiagram,
  MoE: MoEDiagram,
  InferenceServing: InferenceServingDiagram,
  AIEconomics: AIEconomicsDiagram,
  EvalStack: EvalStackDiagram,
  ReasoningCompute: ReasoningComputeDiagram,
  GenerativeArchitectures: GenerativeArchitecturesDiagram,
  MultimodalUnderstanding: MultimodalUnderstandingDiagram,
  AlignmentStack: AlignmentStackDiagram,
  GovernanceLandscape: GovernanceLandscapeDiagram,
  ContextEngineering: ContextEngineeringDiagram,
  AISecurityFrameworks: AISecurityFrameworksDiagram,
  SpeechAudio: SpeechAudioDiagram,
  ExplainabilityLayers: ExplainabilityLayersDiagram,
  AccountabilityChain: AccountabilityChainDiagram,
  WhyNow: WhyNowDiagram,
  HorizonMap: HorizonMapDiagram,
  CareAIMap: CareAIMapDiagram,
  PilotToProduction: PilotToProductionDiagram,
  DistributionShift: DistributionShiftDiagram,
  ClinicalEvidenceLadder: ClinicalEvidenceLadderDiagram,
  SaMDGovernance: SaMDGovernanceDiagram,
  LegalTaskSuitability: LegalTaskSuitabilityDiagram,
  CitationVerification: CitationVerificationDiagram,
  HallucinatedCitation: HallucinatedCitationDiagram,
  PrivilegeDataFlow: PrivilegeDataFlowDiagram,
  FirmAIPolicy: FirmAIPolicyDiagram,
  NextWordPrediction: NextWordPredictionDiagram,
  TrainingVsUsing: TrainingVsUsingDiagram,
  PromptAnatomy: PromptAnatomyDiagram,
  VerifyBeforeYouShare: VerifyBeforeYouShareDiagram,
  DigitalFootprint: DigitalFootprintDiagram,
  EvalDrivenLoop: EvalDrivenLoopDiagram,
  GoldenDataset: GoldenDatasetDiagram,
  LLMJudgeBias: LLMJudgeBiasDiagram,
  RegressionSuite: RegressionSuiteDiagram,
  RedTeamLoop: RedTeamLoopDiagram,
  TokensAndContext: TokensAndContextDiagram,
  RecommendationFeed: RecommendationFeedDiagram,
  ConsentAndImages: ConsentAndImagesDiagram,
  GoodhartsTrap: GoodhartsTrapDiagram,
  NonDeterminismTesting: NonDeterminismTestingDiagram,
  AmbientScribeFlow: AmbientScribeFlowDiagram,
  AutomationBias: AutomationBiasDiagram,
  ClauseExtraction: ClauseExtractionDiagram,
  RetrievalLimits: RetrievalLimitsDiagram,
  SupervisionChain: SupervisionChainDiagram,
  WhyItMakesThingsUp: WhyItMakesThingsUpDiagram,
  AcademicHonestyLine: AcademicHonestyLineDiagram,
  SkillsShift: SkillsShiftDiagram,
  BenchmarkHonesty: BenchmarkHonestyDiagram,
  TaskVsQualityMetrics: TaskVsQualityMetricsDiagram,
  ObservabilityLoop: ObservabilityLoopDiagram,
  SensitivitySpecificity: SensitivitySpecificityDiagram,
  LocalValidation: LocalValidationDiagram,
  TARPrecedent: TARPrecedentDiagram,
  HumanReviewProtocol: HumanReviewProtocolDiagram,
  SyntheticMediaTypes: SyntheticMediaTypesDiagram,
  BiasInEverydayAI: BiasInEverydayAIDiagram,
  AICareerMap: AICareerMapDiagram,
  EvalStatistics: EvalStatisticsDiagram,
  JailbreakTaxonomy: JailbreakTaxonomyDiagram,
  CostLatencyFrontier: CostLatencyFrontierDiagram,
  ReaderAssistanceModes: ReaderAssistanceModesDiagram,
  ClinicalDriftMonitoring: ClinicalDriftMonitoringDiagram,
  ModelChangeControl: ModelChangeControlDiagram,
  ReviewBurdenShift: ReviewBurdenShiftDiagram,
  CheckingAIOutput: CheckingAIOutputDiagram,
  MisinformationScale: MisinformationScaleDiagram,
  AmplifierNotReplacement: AmplifierNotReplacementDiagram,
  EvalsAsUnitTests: EvalsAsUnitTestsDiagram,
  SourcingEvalCases: SourcingEvalCasesDiagram,
  SafetyDisclosureFlow: SafetyDisclosureFlowDiagram,
  ImagingAICapabilities: ImagingAICapabilitiesDiagram,
  HealthDatasetBias: HealthDatasetBiasDiagram,
  ClinicalGovernanceCommittee: ClinicalGovernanceCommitteeDiagram,
  DiligenceAtVolume: DiligenceAtVolumeDiagram,
  StudyingWithAI: StudyingWithAIDiagram,
  WhenNotToUseAI: WhenNotToUseAIDiagram,
  ScepticalNotParanoid: ScepticalNotParanoidDiagram,
  FootprintOverTime: FootprintOverTimeDiagram,
  WhatToStudy: WhatToStudyDiagram,
  KeepLearning: KeepLearningDiagram,
  VibesDontScale: VibesDontScaleDiagram,
  CostOfNoEvals: CostOfNoEvalsDiagram,
  SharedRubric: SharedRubricDiagram,
  CIForPromptsAndAgents: CIForPromptsAndAgentsDiagram,
  AutomatedRedTeamLimits: AutomatedRedTeamLimitsDiagram,
  AUCvsUtility: AUCvsUtilityDiagram,
  CourseScopeSafety: CourseScopeSafetyDiagram,
  DecisionSupportSpectrum: DecisionSupportSpectrumDiagram,
  RegulatoryLandscapeHC: RegulatoryLandscapeHCDiagram,
  DeidentificationConsent: DeidentificationConsentDiagram,
  LegalScopeSafety: LegalScopeSafetyDiagram,
  WhyLegalExposed: WhyLegalExposedDiagram,
  RedliningFlow: RedliningFlowDiagram,
  SanctionsPattern: SanctionsPatternDiagram,
  SupervisingJuniors: SupervisingJuniorsDiagram,
  TechCompetence: TechCompetenceDiagram,
  BillingConsentMalpractice: BillingConsentMalpracticeDiagram,
  SOCTriageScenario: SOCTriageScenarioDiagram,
  SOCBreachScenario: SOCBreachScenarioDiagram,
  SOCPatchScenario: SOCPatchScenarioDiagram,
  LoopOwnership: LoopOwnershipDiagram,
  RunTermination: RunTerminationDiagram,
  AgentBudgets: AgentBudgetsDiagram,
  StuckAgentDetection: StuckAgentDetectionDiagram,
  ScriptVsAgent: ScriptVsAgentDiagram,
  ContextAssembly: ContextAssemblyDiagram,
  ContextCuration: ContextCurationDiagram,
  ContextOrdering: ContextOrderingDiagram,
  ContextCompaction: ContextCompactionDiagram,
  MemoryLifetimes: MemoryLifetimesDiagram,
  CacheAwareLayout: CacheAwareLayoutDiagram,
  ToolApiDesign: ToolApiDesignDiagram,
  ToolSchemas: ToolSchemasDiagram,
  ToolReturnRecovery: ToolReturnRecoveryDiagram,
  ToolErrorsSideEffects: ToolErrorsSideEffectsDiagram,
  LoopVerification: LoopVerificationDiagram,
  SubAgentDelegation: SubAgentDelegationDiagram,
  NonDeterminism: NonDeterminismDiagram,
  RunTracing: RunTracingDiagram,
  AgentFailureTaxonomy: AgentFailureTaxonomyDiagram,
  CostLatencyRequirements: CostLatencyRequirementsDiagram,
  GracefulDegradation: GracefulDegradationDiagram,
  AgentLogging: AgentLoggingDiagram,
  ApprovalGateDesign: ApprovalGateDesignDiagram,
  EscalationOutcome: EscalationOutcomeDiagram,
  RunPresentation: RunPresentationDiagram,
  TrustCurve: TrustCurveDiagram,
  OversightAtVolume: OversightAtVolumeDiagram,
  ForbiddenActions: ForbiddenActionsDiagram,
  VibecodingMeaning: VibecodingMeaningDiagram,
  WhatYouCanBuild: WhatYouCanBuildDiagram,
  WhatNotToBuild: WhatNotToBuildDiagram,
  WeekendSizing: WeekendSizingDiagram,
  PrototypeStages: PrototypeStagesDiagram,
  VibecodingTools: VibecodingToolsDiagram,
  PlainLanguageSpec: PlainLanguageSpecDiagram,
  OneThingAtATime: OneThingAtATimeDiagram,
  ScreensAndFlows: ScreensAndFlowsDiagram,
  NotWhatYouPictured: NotWhatYouPicturedDiagram,
  DescribeTheGap: DescribeTheGapDiagram,
  BreakingIsNormal: BreakingIsNormalDiagram,
  ReadingErrors: ReadingErrorsDiagram,
  GivingAIContext: GivingAIContextDiagram,
  DoomLoop: DoomLoopDiagram,
  WrongTool: WrongToolDiagram,
  GoodLooksLike: GoodLooksLikeDiagram,
  WholeListEveryTime: WholeListEveryTimeDiagram,
  TestWithOthers: TestWithOthersDiagram,
  WorkedWhenITried: WorkedWhenITriedDiagram,
  AIFeatureWrong: AIFeatureWrongDiagram,
  OtherPeoplesData: OtherPeoplesDataDiagram,
  SecretsAndKeys: SecretsAndKeysDiagram,
  RunawayCosts: RunawayCostsDiagram,
  WorksOnMyMachine: WorksOnMyMachineDiagram,
  UnreadableCode: UnreadableCodeDiagram,
  ClassicThreatModels: ClassicThreatModelsDiagram,
  AIAttackSurfaceMap: AIAttackSurfaceMapDiagram,
  UntrustedModelBoundary: UntrustedModelBoundaryDiagram,
  LLMDataFlow: LLMDataFlowDiagram,
  MitreAtlas: MitreAtlasDiagram,
  AcceptedRisks: AcceptedRisksDiagram,
  PromptInjectionDepth: PromptInjectionDepthDiagram,
  IndirectInjection: IndirectInjectionDiagram,
  LethalTrifecta: LethalTrifectaDiagram,
  ToolPoisoning: ToolPoisoningDiagram,
  MemoryContamination: MemoryContaminationDiagram,
  ExcessiveAgency: ExcessiveAgencyDiagram,
  AgentLeastPrivilege: AgentLeastPrivilegeDiagram,
  SandboxEgress: SandboxEgressDiagram,
  IrreversibleActionGates: IrreversibleActionGatesDiagram,
  StructuredOutputControl: StructuredOutputControlDiagram,
  GuardrailModels: GuardrailModelsDiagram,
  DefenseInDepthAI: DefenseInDepthAIDiagram,
  AuthorisedExercise: AuthorisedExerciseDiagram,
  SecurityRegressionCI: SecurityRegressionCIDiagram,
  AutoAdversarialTesting: AutoAdversarialTestingDiagram,
  AIIncidentDetection: AIIncidentDetectionDiagram,
  ModelIncidentResponse: ModelIncidentResponseDiagram,
  PostIncidentGovernance: PostIncidentGovernanceDiagram,
  EverythingInTheBox: EverythingInTheBoxDiagram,
  NoMemory: NoMemoryDiagram,
  WordingMatters: WordingMattersDiagram,
  CommonPromptMistake: CommonPromptMistakeDiagram,
  RolePerspective: RolePerspectiveDiagram,
  ContextConstraints: ContextConstraintsDiagram,
  TaskAsOutcome: TaskAsOutcomeDiagram,
  ShowDontTell: ShowDontTellDiagram,
  ReasoningFirst: ReasoningFirstDiagram,
  AskForStructure: AskForStructureDiagram,
  LengthAndTone: LengthAndToneDiagram,
  EditableDrafts: EditableDraftsDiagram,
  MakeItAskQuestions: MakeItAskQuestionsDiagram,
  FourReasonsBad: FourReasonsBadDiagram,
  DescribeAnswerGap: DescribeAnswerGapDiagram,
  SycophancyTrap: SycophancyTrapDiagram,
  ConfidentFabrication: ConfidentFabricationDiagram,
  ModelSimplyWrong: ModelSimplyWrongDiagram,
  ReusablePrompts: ReusablePromptsDiagram,
  TeamPromptAssets: TeamPromptAssetsDiagram,
  OwnMaterial: OwnMaterialDiagram,
  PromptingCeiling: PromptingCeilingDiagram,
  DocAnswerTesting: DocAnswerTestingDiagram,
  MultiStepAgentTesting: MultiStepAgentTestingDiagram,
  ScalableHumanReview: ScalableHumanReviewDiagram,
  ProductionTesting: ProductionTestingDiagram,
  QualityCostLatency: QualityCostLatencyDiagram,
  EvalTeamHabit: EvalTeamHabitDiagram,
  LLMGovernanceLayers: LLMGovernanceLayersDiagram,
  AIMisconceptions: AIMisconceptionsDiagram,
  LLMInfrastructure: LLMInfrastructureDiagram,
  VendorDueDiligence: VendorDueDiligenceDiagram,
  SkepticalDemo: SkepticalDemoDiagram,
  VendorPushback: VendorPushbackDiagram,
  HonestBusinessCase: HonestBusinessCaseDiagram,
  BuyerSituations: BuyerSituationsDiagram,
  SecurityPrompting: SecurityPromptingDiagram,
  FirstUseCase: FirstUseCaseDiagram,
  ProvingPilot: ProvingPilotDiagram,
  SOCMetrics: SOCMetricsDiagram,
  AnalystRoleShift: AnalystRoleShiftDiagram,
  StagedAutonomy: StagedAutonomyDiagram,
  CapstoneWalkthrough: CapstoneWalkthroughDiagram,
  HealthSourceLadder: HealthSourceLadderDiagram,
  LegalSourceLadder: LegalSourceLadderDiagram,
  HonestMapFinance: HonestMapFinanceDiagram,
  ModelsNotNew: ModelsNotNewDiagram,
  WhereItHelpsFinance: WhereItHelpsFinanceDiagram,
  WherePilotsDie: WherePilotsDieDiagram,
  OfficeRiskProfile: OfficeRiskProfileDiagram,
  ModelRiskFrame: ModelRiskFrameDiagram,
  ExplainThisDecision: ExplainThisDecisionDiagram,
  ProxyDiscrimination: ProxyDiscriminationDiagram,
  ModelInventory: ModelInventoryDiagram,
  VendorModelRisk: VendorModelRiskDiagram,
  ConfidentWrongNumbers: ConfidentWrongNumbersDiagram,
  BacktestOverfitting: BacktestOverfittingDiagram,
  LeakageLookAhead: LeakageLookAheadDiagram,
  RegimeChange: RegimeChangeDiagram,
  CorrelatedModels: CorrelatedModelsDiagram,
  HumanInTheDecision: HumanInTheDecisionDiagram,
  WhatYouPasteFinance: WhatYouPasteFinanceDiagram,
  RecordsSupervision: RecordsSupervisionDiagram,
  GovernanceCase: GovernanceCaseDiagram,
  FinanceSourceLadder: FinanceSourceLadderDiagram,
  ProductBehindTheDemo: ProductBehindTheDemoDiagram,
  AskDontImagine: AskDontImagineDiagram,
  NotList: NotListDiagram,
  StagePlanLedger: StagePlanLedgerDiagram,
  CollapsedSlice: CollapsedSliceDiagram,
  DemoVsProductWorks: DemoVsProductWorksDiagram,
  ChecksWhileYouSleep: ChecksWhileYouSleepDiagram,
  LedgerAfterDemo: LedgerAfterDemoDiagram,
  WhereDataLives: WhereDataLivesDiagram,
  MigrationsBackups: MigrationsBackupsDiagram,
  AccountsAndResets: AccountsAndResetsDiagram,
  HiddenServices: HiddenServicesDiagram,
  BelowScreenLedger: BelowScreenLedgerDiagram,
  DeployRollback: DeployRollbackDiagram,
  ShippingPipelinePlain: ShippingPipelinePlainDiagram,
  KnowingItBroke: KnowingItBrokeDiagram,
  CostAtRealUsage: CostAtRealUsageDiagram,
  ElevenPmEmail: ElevenPmEmailDiagram,
  SoftwareRot: SoftwareRotDiagram,
  HandoverTest: HandoverTestDiagram,
  WeekendVsRealProduct: WeekendVsRealProductDiagram,
  GenuinelyShippable: GenuinelyShippableDiagram,
  AuditScopeSafety: AuditScopeSafetyDiagram,
  AuditAIMap: AuditAIMapDiagram,
  FullPopulationTesting: FullPopulationTestingDiagram,
  AuditExposure: AuditExposureDiagram,
  AuditPilotsDie: AuditPilotsDieDiagram,
  ScepticismVsTool: ScepticismVsToolDiagram,
  EvidenceNotOutput: EvidenceNotOutputDiagram,
  WorkpaperQuestion: WorkpaperQuestionDiagram,
  AuditPasteProblem: AuditPasteProblemDiagram,
  AuditReviewAtVolume: AuditReviewAtVolumeDiagram,
  ModelBehindTheNumber: ModelBehindTheNumberDiagram,
  ClientAIInventory: ClientAIInventoryDiagram,
  BlackBoxEstimate: BlackBoxEstimateDiagram,
  ModelInControl: ModelInControlDiagram,
  ManagementAIConversation: ManagementAIConversationDiagram,
  InspectorQuestion: InspectorQuestionDiagram,
  ToolBeforeReliance: ToolBeforeRelianceDiagram,
  RecurringEngagementDrift: RecurringEngagementDriftDiagram,
  AuditJobShift: AuditJobShiftDiagram,
  AuditSourceLadder: AuditSourceLadderDiagram,
};
